In [3]:
from keras.models import Sequential
from keras.layers import Dense, Activation

1. Sequential model

In [6]:
model = Sequential()
model.add(Dense(512, activation ='relu',input_shape= (784,)))

dropout layer

In [11]:
from keras.models import Sequential 
from keras.layers import Dense, Activation, Dropout #model = Sequential() 
model.add(Dense(512, activation = 'relu', input_shape = (784,))) 
model.add(Dropout(0.2)) 
## or
model.add(Dense(512, activation = 'relu'))
model.add(Dropout(0.2)) 
model.add(Dense(512, activation = 'softmax'))

Backend module

In [15]:
from keras import backend as k
print(k.backend())
print(k.epsilon())
print(k.image_data_format())
print(k.floatx())

tensorflow
1e-07
channels_last
float32


In [16]:
print(k.get_uid(prefix=''))
print(k.reset_uids())
print(k.get_uid(prefix=''))

data = k.placeholder(shape = (1,3,3))
data

1
None
1


<KerasTensor: shape=(1, 3, 3) dtype=float32 (created by layer 'input_1')>

In [18]:
#dot
a = k.placeholder(shape = (4,2))
b = k.placeholder(shape = (2,3)) 
c = k.dot(a,b) 
c

<KerasTensor: shape=(4, 3) dtype=float32 (created by layer 'tf.linalg.matmul_1')>

In [19]:
res = k.ones(shape = (2,2))
k.eval(res) 

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [21]:
a_batch = k.ones(shape = (2,3)) 
b_batch = k.ones(shape = (2,3))
c_batch = k.batch_dot(a_batch,b_batch);c_batch 

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[3.],
       [3.]], dtype=float32)>

In [22]:
data = k.variable([[10,20,30,40],[50,60,70,80]])
result = k.transpose(data);result

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[10., 50.],
       [20., 60.],
       [30., 70.],
       [40., 80.]], dtype=float32)>

In [23]:
print(k.eval(result))

[[10. 50.]
 [20. 60.]
 [30. 70.]
 [40. 80.]]


In [25]:
import numpy as np
data = np.array([[10,20,30,40],[50,60,70,80]]) 
print(np.transpose(data))
res = k.variable(value = data);print(res)

[[10 50]
 [20 60]
 [30 70]
 [40 80]]
<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[10., 20., 30., 40.],
       [50., 60., 70., 80.]], dtype=float32)>


In [27]:
a = k.placeholder((2, 2), sparse=True);print(a)
a = k.placeholder((2, 2), sparse=True)

KerasTensor(type_spec=SparseTensorSpec(TensorShape([2, 2]), tf.float32), description="created by layer 'input_7'")


In [29]:
b = k.to_dense(a);print(b) 
print(k.is_sparse(b))

KerasTensor(type_spec=TensorSpec(shape=(None, None), dtype=tf.float32, name=None), name='tf.keras.backend.to_dense_1/SparseToDense:0', description="created by layer 'tf.keras.backend.to_dense_1'")
False


uniform distribution

In [30]:
a = k.random_uniform_variable(shape = (2, 3), low=0, high = 1)
b = k. random_uniform_variable(shape = (3,2), low = 0, high = 1)
c = k.dot(a, b)
k.int_shape(c)

(2, 2)

In [48]:
from keras.utils import metrics_utils
dir(metrics_utils)
# data = metrics_utils('data.hdf5', 'data');data

['AUCCurve',
 'AUCSummationMethod',
 'ConfusionMatrix',
 'Enum',
 'NEG_INF',
 'Reduction',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_assert_splits_match',
 '_filter_top_k',
 '_update_confusion_matrix_variables_optimized',
 'assert_thresholds_range',
 'backend',
 'functools',
 'is_evenly_distributed_thresholds',
 'losses_utils',
 'np',
 'parse_init_thresholds',
 'ragged_assert_compatible_and_get_flat_values',
 'result_wrapper',
 'tf',
 'tf_utils',
 'to_list',
 'update_confusion_matrix_variables',
 'update_state_wrapper',
 'weakmethod',
 'weakref']

In [44]:
import keras.utils 
dir(keras.utils)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'all_utils',
 'control_flow_util',
 'conv_utils',
 'data_utils',
 'dataset_creator',
 'generic_utils',
 'io_utils',
 'layer_utils',
 'losses_utils',
 'metrics_utils',
 'mode_keys',
 'multi_gpu_utils',
 'np_utils',
 'object_identity',
 'tf_contextlib',
 'tf_inspect',
 'tf_utils',
 'version_utils',
 'vis_utils']

In [51]:
from keras.utils import print_summary 
print_summary(model)

ImportError: cannot import name 'print_summary' from 'keras.utils' (/home/syedasamreen/.local/lib/python3.8/site-packages/keras/utils/__init__.py)

In [50]:
from keras.utils import plot_model 
plot_model(model,to_file = 'image.png')

ImportError: cannot import name 'plot_model' from 'keras.utils' (/home/syedasamreen/.local/lib/python3.8/site-packages/keras/utils/__init__.py)

In [ ]:
from keras.models import Sequential 
from keras.layers import Activation, Dense 
from keras import initializers 
from keras import regularizers 
from keras import constraints 

model = Sequential() 

model.add(Dense(32, input_shape=(16,), kernel_initializer = 'he_uniform', kernel_regularizer = None, kernel_constraint = 'MaxNorm', activation = 'relu')) 
model.add(Dense(16, activation = 'relu')) 
model.add(Dense(8))

In [88]:
import subprocess
file='/home/syedasamreen/ipcred.txt'
with open(file,'r') as f:
    creds = f.readlines()
    f.close()
ip1 = creds[0];print(ip1)
usr1 = creds[1]
pwd1 = creds[2]
command1 = 'ipmitool -I lanplus -H '+ip1+' -U '+usr1+' -P '+pwd1+' chassis status'
print(command1)
chasie_output = subprocess.getoutput(command1) 
print(chasie_output)

10.1.0.29

ipmitool -I lanplus -H 10.1.0.29
 -U 'root'
 -P 'IDRAC@v!gy@nlabs'
 chassis status
Password: Error: Unable to establish IPMI v2 / RMCP+ session
/bin/sh: 2: -U: not found
/bin/sh: 3: -P: not found
/bin/sh: 4: chassis: not found
